name: Monitor Cardmarket Price

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch: # Permite ejecutarlo manualmente para testear

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          CARD_URL: ${{ secrets.CARD_URL }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python scraper.py
